use_frameworks!

target 'LinEqua_Example' do
  pod 'LinEqua', :path => '../'

  target 'LinEqua_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.0.0'
#  pod 'Nimble', '~> 5.1.1'
  end
end
